name: chess_puzzle_game
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  page_transition: ^2.1.0

  cupertino_icons: ^1.0.8
  rolling_bottom_bar: ^0.2.2
  pageviewj: ^0.0.3
  http: ^1.2.2
  cloud_firestore: ^4.17.5
  provider: ^6.1.2
  firebase_core: ^2.32.0
  collection: ^1.18.0
  font_awesome_flutter: ^10.7.0
  uni_color_name: ^0.7.0
  loading_animation_widget: ^1.3.0
  flutter_dotenv: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - images/
    - .env
